# Dev server
run:
	npm run start

# Dev server (test mode)
run-test:
	npm run start-test

# Local Parse server
parse-server:
	npm run server

# Acceptance test
test:
	npm run test

# Acceptance test (watch)
test-watch:
	npm run test-watch
