all:
	@echo "run:			meteor npm start"
	@echo "parse-server:		meteor npm run server"
	@echo "run-test:		meteor npm run test"
	@echo "test-watch:		meteor npm run test-watch"

# Dev server
run:
	meteor npm start

# Local Parse server
parse-server:
	meteor npm run server

# Acceptance test
test:
	npm run chimp-test

# Acceptance test (watch)
test-watch:
	npm run chimp-watch
